package actions;

public enum ActionType {
    ADD_CONSUMERS, UPDATE_DISTRIBUTORS, UPDATE_PRODUCERS,
    RECEIVE_SALARY, CHOOSE_PRODUCERS, COMPUTE_PRODUCTION_COST,
    COMPUTE_CONTRACT_PRICES, REMOVE_EXPIRED_CONTRACTS,
    CHOOSE_CONTRACTS, PAY_CONTRACTS, PAY_EXPENSES, UPDATE_CONTRACTS,
    CREATE_MONTHLY_STAT
}
